### model
model_name_or_path: /root/models/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: sft_train_trace
template: qwen3
cutoff_len: 10240
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4
use_span_masking: true 
mask_span_types: "tool_response"

### output
output_dir: /root/output/search_agent-SFT
logging_steps: 1
save_strategy: "epoch"
# save_steps: 2
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### visualize
report_to: swanlab
use_swanlab: True
swanlab_project: llamafactory
swanlab_workspace: logs/
swanlab_run_name: test
swanlab_mode: local
# swanlab_api_key:


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
weight_decay: 0.00
gradient_checkpointing: true

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
