tools:
  - class_name: "verl.tools.custom_search_tool.CustomSearchTool"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "google_search"
        description: "Searches for relevant information based on queries."
        parameters:
          type: "object"
          properties:
            query_list:
              type: "array"
              items:
                type: "string"
              description: "List of search queries"
          required: ["query_list"]